### ISSUE TITLE
login form

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#1]
# Value Proposition

As a user
I need to put in my details
to be able to enter the LogBuddy-App

## Description

![LogBuddy EnterForm(1)](https://user-images.githubusercontent.com/91341532/159584454-fc0dc60a-9e07-4271-9cf7-6836e32154c7.svg)

## Acceptance Criteria
- [ ] if name and/or date of birth is empty cant save details
- [ ] all inputs have a max length of 50
- [ ] date of birth input is type date
- [ ] all whitespaces are trimmed
- [ ] on save details, details will be submited to main page

## Tasks
- [ ] create branch "login-form"
- [ ] create login-form component with storybook
- [ ] write specs for login form
- [ ] add styles
- [ ] check in other browser
