### ISSUE TITLE
Delete Modal

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#13]
# Value Proposition

**As a** user
**I need to** confirm my delete click
**to be able to** doublecheck my choice.

# Description

![ModalDelete(1)](https://user-images.githubusercontent.com/91341532/161429913-9fab71f5-930d-45a4-b097-86592e08b7df.png)

# Acceptance Criteria
- [x] confirm the delete choice in a pop up window after clicking delete button

# Tasks
- [x] create branch "deletemodal"
- [x] create ModalDelete component
- [x] write storybook for ModalDelete
- [x] write spec for ModalDelete
- [x] update "DiveLog" component
- [x] add styles
- [x] update App
- [x] check in other browser
