### ISSUE TITLE
dive-statistics max. depth details

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#14]
# Value Proposition

**As a** user
**I need to** have an overview of my dive statistics
**to be able to** find my most interesting dives immediately.

# Description

![Modal-maxdepth(1)](https://user-images.githubusercontent.com/91341532/161431748-142c9a38-63ec-40ae-9be2-3832b9f106a6.png)

# Acceptance Criteria
- [x] max. depth button will unfold by clicking and show all details of that dive

# Tasks
- [x] create branch "max-depthdetails"
- [x] write "divestatistics" component
- [x] write storybook for "divestatistics"
- [x] write specs for "divestatistics"
- [x] add styles
- [x] update App
- [x] check in other browser
