### ISSUE TITLE
create new diver

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#15]
# Value Proposition

**As a** user
**I need to** find my personal dive details quick
**to be able to** show them to any divecenter.

# Description

![create-profile](https://user-images.githubusercontent.com/91341532/161436031-c0fe306e-304d-4219-8e4e-7597f24d7b94.png)

# Acceptance Criteria
- [x] if no personal details are given it shows a "create new diver" button at the top of the page
- [x] on "create new diver" the formular opens
- [x] if personal details are given it shows them at the top of the page
- [x] only the name is mandatory
- [x] all inputs have a max length of 50 characters
- [x] date input is type date
- [x] all whitespaces are trimmed

# Tasks
- [x] create branch "createDiver"
- [x] write "diverform" component
- [x] write storybook for "diverform"
- [x] write specs for "diverform"
- [x] add styles
- [x] update App
- [x] check in other browser
