### ISSUE TITLE
DiveLogs

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#2]
# Value Proposition

**As a** user
**I need to** have a list of my past dives
**to be able to** keep track of the number of dives. 

# Description

![divelog-list](https://user-images.githubusercontent.com/91341532/159939309-6db9e3a5-e329-45f6-b5af-f69121e8173a.svg)

# Acceptance Criteria
- [x] list of dives is scrollable

# Tasks
- [x] create branch "dive-log"
- [x] create "DiveLog" component
- [x] create storybook for "DiveLog"
- [x] write specs for "DiveLog"
- [x] update App
- [x] add styles
- [x] check in other browser
