### ISSUE TITLE
pictureupload

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#21]
# Value Proposition

**As a** user
**I need to** add a profile-picture
**to be able to** verify myself and my dives.

# Description

![create-profilepic](https://user-images.githubusercontent.com/91341532/162282561-22f63f88-147d-4efe-a3e3-737cc60fa900.png)

# Acceptance Criteria
- [x] the user can upload a photo from his/her data by clicking on "upload photo"
- [x] the chosen picture will be shown before saving
- [x] after saving the picture will show up on the main page

# Tasks
- [x] create branch "pictureupload"
- [x] update "diverform" component
- [x] update storybook for "diverform"
- [x] update specs for "diverform"
- [x] add styles
- [x] update App
- [x] check in other browser
