### ISSUE TITLE
certifications

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#22]
# Value Proposition

**As a** user
**I need to** upload a picture of my certifications
**to be able to** verify how qualified I am.

# Description

![certifications](https://user-images.githubusercontent.com/91341532/162285415-0dbb7610-a88b-45fb-b218-34535276d4b2.png)

# Acceptance Criteria
- [ ] the user can upload a photo from his/her data by clicking on "add certification"

# Tasks
- [ ] create branch "certifications"
- [ ] write "certifications" component
- [ ] write storybook for "certifications"
- [ ] write specs for "certifications"
- [ ] add styles
- [ ] update App
- [ ] check in other browser
