### ISSUE TITLE
Edit diverinformation

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#24]
# Value Proposition

**As a** user
**I need to** edit my personal information
**to be able to** update my certification status or organization.

# Description

![edit](https://user-images.githubusercontent.com/91341532/162454516-8b1da2c4-c484-483d-8d6f-4df1c3733aeb.png)

# Acceptance Criteria
- [x] the create diver form will open with the old details filled in the inputs when clicking on the edit button
- [x] the new details will be shown when saving the changes

# Tasks
- [x] create branch "editDiver"
- [x] update "home" component
- [x] update storybook for "home"
- [x] write specs for "home"
- [x] add styles
- [x] update App
- [x] check in other browser
