### ISSUE TITLE
delete certificate

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#25]
# Value Proposition

**As a** user
**I need to** delete my pictures of certificates
**to be able to** correct mistakes or wrong pictures

# Description

![delete-certificate(1)](https://user-images.githubusercontent.com/91341532/162562869-7a8bea49-0a49-4b23-a7f0-756932017a4e.png)

# Acceptance Criteria
- [x] when clicking the delete button a modal will show up and asks for confirmation
- [x] after confirming the pic will be deleted immediately

# Tasks
- [x] create branch "deletecert"
- [x] update "certificates" component
- [x] update storybook for "certificates"
- [x] write specs for "certificates"
- [x] add styles
- [x] update App
- [x] check in other browser
