### ISSUE TITLE
edit divelog

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#27]
# Value Proposition

**As a** user
**I need to** edit my divelogs
**to be able to** correct mistakes and add information.

# Description

![edit-divelog](https://user-images.githubusercontent.com/91341532/162612483-e1f5524a-ab64-4310-83be-2fc163784b69.png)

# Acceptance Criteria
- [x] on edit click the form will open prefilled with all the data from that dive
- [x] on save the information will overwrite the old data

# Tasks
- [x] create branch "editdive"
- [x] update "divelog" component
- [x] update "add dive" component
- [x] update storybook for "divelog"
- [x] update specs for "divelog"
- [x] add styles
- [x] update App
- [x] check in other browser
