### ISSUE TITLE
location map form

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#28]
# Value Proposition

**As a** user
**I need to** find my divespot on a map
**to be able to** find the exact location afterwards.

# Description

![location-map(1)](https://user-images.githubusercontent.com/91341532/162613870-a336cd60-985a-4365-a247-4bb33ded80d6.png)

# Acceptance Criteria
- [x] on "map" click a map will open with a search option
- [x] the user can pinpoint a location which will be saved on map and in word

# Tasks
- [x] create branch "maplocation"
- [x] add map component
- [x] update "divelog" component
- [x] update "add dive" component
- [x] update storybook for "divelog"
- [x] update specs for "divelog"
- [x] add styles
- [x] update App
- [x] check in other browser
