### ISSUE TITLE
divelog map

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#29]
# Value Proposition

**As a** user
**I need to** find my divespot on a map
**to be able to** to find the exact location afterwards.

# Description

![divelog-map](https://user-images.githubusercontent.com/91341532/162614702-25eb4114-ac1f-44f1-9c2a-bb3c7cfb0f2e.png)

# Acceptance Criteria
- [x] on save dive the location will be shown on a map in the divelog

# Tasks
- [x] create branch "divelog-map"
- [x] add map component
- [x] update "divelog" component
- [x] update "add dive" component
- [x] update storybook for "divelog"
- [x] update specs for "divelog"
- [x] add styles
- [x] update App
- [x] check in other browser
