### ISSUE TITLE
Create new DiveLog

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#3]
# Value Proposition

**As a** user
**I need to** log new dives
**to be able to** keep my logbook updated

# Description

![LogNewDive](https://user-images.githubusercontent.com/91341532/160380905-d8b608f2-1e69-4379-856f-2b0d9b0da4f3.svg)

# Acceptance Criteria
- [x] all information except notes are mandatory
- [x] all inputs except notes have a max length of 50 characters
- [x] notes has a max length of 500 characters
- [x] date input is type date
- [x] all time inputs are type time
- [x] all whitespaces are trimmed
- [x] on "add dive" the log dive formular opens
- [x] on "log dive", a new card shows up in first position at divlogs
- [x] all information will be rendered in the extended divelog-details

# Tasks
- [x] create branch "log-dive"
- [x] create "DiveLogForm" component
- [x] create storybook for "DiveLogForm"
- [x] write specs for "DiveLogForm"
- [x] create three button components
- [x] create storybooks for buttons
- [x] write specs for buttons
- [x] add "add-dive-button" to Dive Logs
- [x] switch to DiveLogForm with conditional rendering by clicking "add Dive"
- [x] switch to Dive Logs with conditional rendering by clicking the "back" button
- [x] update App
- [x] add styles
- [x] check in other browser
