### ISSUE TITLE
Add pictures to divelog

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#32]
# Value Proposition

**As a** user
**I need to** save pictures in my  divelog
**to be able to** to remember how beautiful it was and what exactly saw.

# Description

![divelogpictures](https://user-images.githubusercontent.com/91341532/162914764-02aa8e17-aed3-485e-97f4-3525a7098022.png)

# Acceptance Criteria
- [x] the user can upload a photo from his/her data by clicking on "upload picture"
- [x] on save the pictures will be shown on the extended divecard

# Tasks
- [x] create branch "divelogpics"
- [x] update "AddDive" and "DiveLog" component
- [x] update storybook for "AddDive" and "DiveLog"
- [x] add styles
- [x] update App
- [x] check in other browser
