### ISSUE TITLE
divelog-details

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#4]
# Value Proposition

**As a** user
**I need to** see all important details of my past dives
**to be able to** provide the details to the divecenter

# Description

![divelog-details](https://user-images.githubusercontent.com/91341532/159941450-f694d49e-6f76-4a35-b1da-bc2a63a5143b.svg)

# Acceptance Criteria
- [x] Toggle more/less details by clicking on one card

# Tasks
- [x] create branch "dive-log-details"
- [x] update "DiveLog" component
- [x] update storybook for "DiveLog"
- [x] update specs for "DiveLog"
- [x] update App
- [x] add styles
- [x] check in other browser
