### ISSUE TITLE
Add local storage

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#5]
# Value Proposition

**As a** user
**I need to** have my logs saved
**to be able to** review them at any time.

# Description

![divelog(1)](https://user-images.githubusercontent.com/91341532/159956687-800f988d-482f-4a7c-b9c8-880f57e10553.svg)

# Acceptance Criteria
- [x] the data will be saved and and still be shown after closing and reopening the app

# Tasks
- [x] create branch "localstorage"
- [x] implement localstorage to divelog
- [x] update App
- [x] check in other browser
