### ISSUE TITLE
delete button for divelogs

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#6]
# Value Proposition

**As a** user
**I need to** delete a log
**to be able to** remove wrong ones.

# Description

![delete-button](https://user-images.githubusercontent.com/91341532/159958193-7a656a72-af23-49ae-a60e-2c136e8dda19.svg)

# Acceptance Criteria
- [x] the card will be removed immediately

# Tasks
- [x] create branch "delete-divelog"
- [x] update "DiveLog component
- [x] update storybook for "DiveLog"
- [x] update specs for "DiveLog"
- [x] add styles
- [x] update App
- [x] check in other browser
