### ISSUE TITLE
main-menu

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#7]
# Value Proposition

**As a** user
**I need to** have a menu
**to be able to** navigate through the important topics

# Description

![menu](https://user-images.githubusercontent.com/91341532/160000769-55ca9c75-3da7-4a52-b5c2-d68f0e85c8c4.svg)

# Acceptance Criteria
- [ ] the dives button shows the amount of total dives
- [ ] by clicking the button it navigates to the list of dive logs
- [ ] by clicking on the arrow button on the dive logs page it'll navigate back to th main menu

# Tasks
- [ ] create branch "home"
- [ ] create "home" component
- [ ] create storybook for "home"
- [ ] write specs for "home"
- [ ] create a "back" button
- [ ] implement react-router
- [ ] add styles
- [ ] update App
- [ ] check in other browser
