### ISSUE TITLE
main-menu/max.-depth

### ISSUE THREAD

**Issue by FlyingMoe91** [FlyingMoe91/capstone-project#8]

**Comment by FlyingMoe91** [comment]
# Value Proposition

**As a** user
**I need to** specific button
**to be able to** see my deepest dive

# Description

![menu-maxdepth(1)](https://user-images.githubusercontent.com/91341532/160013768-501fb65d-f658-486f-b108-3e13d73d6917.svg)

# Acceptance Criteria
- [ ] the max. depth button shows the deepest dive of all past logged dives
- [ ] next user story: button will unfold and show all details of that dive

# Tasks
- [ ] create branch "max-depth"
- [ ] update "home" component
- [ ] update storybook for "home"
- [ ] update specs for "home"
- [ ] add styles
- [ ] update App
- [ ] check in other browser
